//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistCL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class CompilerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CompilerSettings defaultInstance = ((CompilerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CompilerSettings())));
        
        public static CompilerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan AgentsUpdatePeriod {
            get {
                return ((global::System.TimeSpan)(this["AgentsUpdatePeriod"]));
            }
            set {
                this["AgentsUpdatePeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:00")]
        public global::System.TimeSpan AgentsSilenceLimit {
            get {
                return ((global::System.TimeSpan)(this["AgentsSilenceLimit"]));
            }
            set {
                this["AgentsSilenceLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string InstanceName {
            get {
                return ((string)(this["InstanceName"]));
            }
            set {
                this["InstanceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:03:00")]
        public global::System.TimeSpan NetworkBuildPeriod {
            get {
                return ((global::System.TimeSpan)(this["NetworkBuildPeriod"]));
            }
            set {
                this["NetworkBuildPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan AgentsFromConfigCheckPeriod {
            get {
                return ((global::System.TimeSpan)(this["AgentsFromConfigCheckPeriod"]));
            }
            set {
                this["AgentsFromConfigCheckPeriod"] = value;
            }
        }
    }
}
